### PR TITLE
Only add Choice Button "cancel" if there is no choice cancel

### PR DESCRIPTION
**Pull request by gustavobca**

### CODE REVIEW

**Comment by vE5li** [comment]
No complaints about the code. Do you know by any chance if other clients to this the same way?

**Comment by gustavobca** [comment]
> No complaints about the code. Do you know by any chance if other clients to this the same way?

No, I just considered it as a bug

**Comment by eleriaqueen** [comment]
I know zero C-Sharp but this code may be related to topic:
[UnityRO - NpcBoxMenuController.cs](https://github.com/guilhermelhr/unityro/blob/dc741a545304265a90d8c27b40a903c6ab316f74/UnityClient/Assets/Scenes/Map/NpcBoxMenuController.cs#L10)

**Comment by vE5li** [comment]
No longer needed since https://github.com/vE5li/korangar/commit/11bc40d4978e264875e36ad068a75842c361c512

**Pull request closed without merging**
