### PR TITLE
Implement custom path finding

### PR DESCRIPTION
**Pull request by hasenbanck**
I found the path finding code highly complicated and also inefficient, since we allocated on the heap multiple times, without amortising the allocations.

This implementation provides a struct that implements the A* and also line of sight path finding in a way, that is compatible with the server implementations. We also re-use the heap allocations.

The A* algorithm is a basic implementation that uses a binary heap. Moved the code in korangar_utils, so that it can be properly optimized and also tested.

### CODE REVIEW

**Comment by eleriaqueen** [comment]
I just tested your PR a minute ago.
Is it possible that moving is bit too slow when going in a straight line, and maybe a bit too fast when doing diagonals ?
Because it feels that way.

**Comment by hasenbanck** [comment]
> I just tested your PR a minute ago. Is it possible that moving is bit too slow when going in a straight line, and maybe a bit too fast when doing diagonals ? Because it feels that way compared to official.

Yes, that is the issue that I talked about in the last paragraph. But fixed that issue in my local branch allready and will upload the fix soon.

**Comment by hasenbanck** [comment]
Should be fixed now and the behavior should be no worse than the old implementation.

**Comment by eleriaqueen** [comment]
Yep fixed, and movement feels pretty good ! 

There is just a little issue that was present in main as well and might be unrelated but when first appearing into the world after character selection, client is probably still loading assets then because movement is super jittery for about 5 seconds.

**Comment by hasenbanck** [comment]
> Yep fixed, and movement feels pretty good !
> 
> There is just a little issue that was present in main as well and may be unrelated but when first appearing into the world after character selection, client is probably still loading assets then because movement is super jittery for about 5 seconds.

I'm not too sure about that. The only thing that could load after you spawned are entities, but even if I spawn in an empty location where no entities are, I get those "desyncs". I think the server doesn't expect the client to move so fast, maybe we need to wait for a specific packet to arrive, until we can send out player commands. That issue is for future investigations though.

**Pull request merged**
